### ISSUE TITLE
BUG: generate_og_timeseries can result in nan

### ISSUE THREAD

**Issue by mekman** [kdesimone/popeye#24]
Hi,

(I might open a couple of issues as I'm getting more familiar with popeye; hope you don't mind)

With my own data I encountered some predictions to be ``nan``. Below is a minimal example to reproduce that problem. This happens when ``generate_og_timeseries`` gets estimates for ``x/y`` that are too far outside of ``stimulus.deg_x.min() / .max()``.

I don't know what's the best way of dealing with that. Do you have any idea?

	# stimulus features
	pixels_across = 800
	pixels_down = 600
	viewing_distance = 38
	screen_width = 25
	thetas = np.arange(0,360,45)
	num_steps = 20
	ecc = 10
	tr_length = 1.0
	frames_per_tr = 1.0
	scale_factor = 0.05
	dtype = ctypes.c_short

	bar = simulate_bar_stimulus(pixels_across, pixels_down, viewing_distance, screen_width, thetas, num_steps, ecc)
	stimulus = VisualStimulus(bar, viewing_distance, screen_width, scale_factor, dtype)

	x = stimulus.deg_x.min()
	y = stimulus.deg_y.min() - 4
	sigma = 1
	beta = 2.5
	hrf_delay = -0.25

	data = og.compute_model_ts(x, y, sigma, beta, hrf_delay,
	                           stimulus.deg_x, stimulus.deg_y, 
	                           stimulus.stim_arr, tr_length)

	print np.all(np.isnan(data))

	#stim = generate_og_timeseries(stimulus.deg_x, stimulus.deg_y, stimulus.stim_arr, x, y, fit.sigma)

**Comment by kdesimone** [comment]
This has been fixed.
