### ISSUE TITLE
naming GausianFit attributes

### ISSUE THREAD

**Issue by mekman** [kdesimone/popeye#27]
Hi,

I really like the way popeye is designed with its fit-class. How would you feel about renaming some class attributes to make the naming more consistent?

```
fit = GaussianFit(...)
```

results ATM in this

```
In [216]: fit.
fit.auto_fit              fit.estimate              fit.prediction            fit.uncorrected_rval
fit.ballpark_estimate     fit.fit_bounds            fit.receptive_field       fit.verbose
fit.beta                  fit.fit_stats             fit.rss                   fit.voxel_index
fit.beta0                 fit.hemodynamic_response  fit.s0                    fit.x
fit.coarse_fit_stats      fit.hrf0                  fit.search_bounds         fit.x0
fit.coarse_prediction     fit.hrf_delay             fit.sigma                 fit.y
fit.data                  fit.model                 fit.tr_length             fit.y0
```

Some of the `ballpark_estimates` have a trailing "0",  e.g. `x0`, `beta0` etc., while others are referred to as "coarse", e.g. `coarse_fit_stats`.

Would it make sense to have rather `fit_stats` and `fit_stats0`, or `fit_stats` and `fit_stats_coarse`, and `x` and `x_coarse` respectively? I personally would have a preference for the latter, as it's more explicit.

NB, ATM there is `fit.sigma` and `fit.s0`, which would probably be better `fit.sigma` and `fit.sigma0`, or `fit.sigma` and `fit.sigma_coarse`.

What I really like about the fit-class for example in scikit-learn is that all attributes that were estimated from the data have a trailing underscore which makes them easily distinguishable from user specified parameters:

```
from sklearn.svm import SVC
from sklearn.datasets import load_digits
clf = SVC()
X = load_digits().data
y = load_digits().target
clf.fit(X,y)
```

Here, parameters like e.g., `clf.C` and `clf.epsilon` were set by the user, while e.g., `clf.coef_` was calculated from the data.

```
In [216]: clf.
clf.C                  clf.dual_coef_         clf.n_support_         clf.score
clf.cache_size         clf.epsilon            clf.nu                 clf.set_params
clf.class_weight       clf.fit                clf.predict            clf.shape_fit_
clf.class_weight_      clf.fit_status_        clf.predict_log_proba  clf.shrinking
clf.classes_           clf.gamma              clf.predict_proba      clf.support_
clf.coef0              clf.get_params         clf.probA_             clf.support_vectors_
clf.coef_              clf.intercept_         clf.probB_             clf.tol
clf.decision_function  clf.kernel             clf.probability        clf.verbose
clf.degree             clf.max_iter           clf.random_state 
```

One could think about using a similar concept in popeye, e.g. using `fit.beta_`, `fit.x_`, and `fit.data`, `fit.hemodynamic_response`.

There are probably more important issues to iron out before going into details like this. However, I was curious to hear whether this makes sense from your point of view?

Cheers,
 Matthias

**Comment by kdesimone** [comment]
Fixed 
https://github.com/kdesimone/popeye/commit/49193554cb22b4df537e8e111a4f7562577afacf
