### ISSUE TITLE
License file missing and other JOSS review comments

### ISSUE THREAD

**Issue by tknapen** [kdesimone/popeye#36]
The JOSS review process requires that the repo contain a plain-text LICENSE file with the contents of an OSI approved software license

- added a license -- https://github.com/kdesimone/popeye/blob/master/LICENSE -KD

**Comment by tknapen** [comment]
I'm not going to open separate issues for this, but the review checklist has at least one other item that necessitates a change in the repo:
Does the release version given match the GitHub release (v.1.0.0)?
So, could you provide a version number?

**Comment by tknapen** [comment]
Also, it would be helpful if you could add guidelines for people (like me) that would like to start contributing to Popeye. The full JOSS question: **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by tknapen** [comment]
One last comment: the forms ask for the references in the paper.md etc to include DOI numbers. Could you add those to the paper.md?

the question: **References**: Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arokem** [comment]
For contributor documentation, this might be helpful: https://github.com/matthew-brett/gitwash

**Comment by tknapen** [comment]
My impression is that if you create a GitHub repo tag/release with the same version number as is listed in the project now, that would finish the review process.

**Comment by kdesimone** [comment]
Here goes: https://zenodo.org/record/176596
