### ISSUE TITLE
Sphinx auto-build not working

### ISSUE THREAD

**Issue by kdesimone** [kdesimone/popeye#41]
I'm sort of lost in this department.  When pushing a new commit, the gh-pages Sphinx docs should rebuild and update, but this doesn't work without manual intervention. Need to revisit.

**Comment by arokem** [comment]
My 2 cents: You probably want the online docs to reflect the currently *released* code. 

For example, right now you would want the docs to be generated from the 0.3.0 tag. When 0.4.0 is tagged, you update the docs, etc. 

This way, the software will work as expected for users who install the software through pip/conda. 

If you do want to build the docs in every PR, the CI server needs to be set up to do that. This package is useful for that: https://pypi.python.org/pypi/doctr

**Comment by kdesimone** [comment]
OK I'll look into it.  Thanks!
