### ISSUE TITLE
Numpy 1.11 requirement

### ISSUE THREAD

**Issue by arokem** [kdesimone/popeye#56]
Discussion that started on #55. From there: "the numpy==1.11 requirement is because of scipy.signal.spectrogram's not complying with the int/float indexing as of
1.12 onward." 

@kdesimone : could you please point out the code where this is happening?

 I can take a look. Would be good not to pin the numpy version if possible.

**Comment by kdesimone** [comment]
OK—this was a little confusing to track down b/c of recent relevant changes in scipy.

The problem originated in popeye's auditory pRF models that relied on scipy.signal.spectrogram. This error is being thrown on numpy>=1.12 and scipy=0.19.1:
```
... /scipy/signal/windows.py", line 890, in tukey 
n2 = n[width+1:M-width-1]
TypeError: slice indices must be integers or None or have an __index__ method
```
This error can be suppressed with a patch that adds  
`M = int(M)` 
directly above this [line](https://github.com/scipy/scipy/blob/56f7975c0b1c28e551f512fb86677486cc7317a6/scipy/signal/windows.py#L888).

Alternatively, you can just require numpy=1.11. This was the solution I incorporated into popeye.

It looks like the folks at scipy are [deprecating the scipy/signal/windows](https://github.com/scipy/scipy/tree/master/scipy/signal/windows), although it's not clear to me if this fixes the problem. I tried to build the developmental scipy 1.0b but the build fails...

`error: Command "g++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/kevin/anaconda3/include -arch x86_64 -I/Users/kevin/anaconda3/include -arch x86_64 -D__STDC_FORMAT_MACROS=1 -Iscipy/sparse/sparsetools -I/Users/kevin/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/Users/kevin/anaconda3/include/python3.6m -c scipy/sparse/sparsetools/csr.cxx -o build/temp.macosx-10.7-x86_64-3.6/scipy/sparse/sparsetools/csr.o -MMD -MF build/temp.macosx-10.7-x86_64-3.6/scipy/sparse/sparsetools/csr.o.d" failed with exit status 1`

I noticed that the flag "-I" is abutted against other arguments in several instances. Adding in whitespaces after -I fixes it, and the command exits with 0. That's great, but I don't know how/where to make the fix to the install recipe writ large.

**Comment by arokem** [comment]
Numpy expects integer indices as of version 1.12. This is rather simple in this case, see #58
