### ISSUE TITLE
Haemodynamics and function of the LGN

### ISSUE THREAD

**Issue by ingo-m** [kdesimone/popeye#59]
Hi @kdesimone,

I just read your [preprint](https://www.preprints.org/manuscript/201806.0413/v1) on spatiotemporal pRF modelling in the LGN - what a great paper. A few years ago, at the beginning of my PhD, I tried some LGN parvo/magno mapping with a simple stimulus design (the usual green/red perceptually isoluminant vs. black & white stimuli) and didn't get much of a differential response, only large signal amplitudes close to vessels in the inferior part of LGN. I moved to cortex instead... I was just about to give it another try and incorporate the contrast response function into the pRF framework (contrast modulated bar stimulus) in order to distinguish magno/parvo populations irrespective of signal amplitude.

I have one question about the temporal component of the pRF model: Besides the fact that it works mathematically, do you think there is any (biological) reason why a single gamma and its first derivative are a plausible model for the sustained & transient components, respectively? I know that the double gamma is the 'canonical' HRF model, but I never thought about a relation to high & low temporal frequency channels at the neuronal level.

Two suggestions regarding the preprint:
- Page 8: shouldn't it read "gradient-echo" instead of "spin-echo" (Magnetization-Prepared RApid *Gradient-Echo* imaging)?
- Page 9: "TR = 3 ms" should probably read "TR = 3 s"?
- In the preprint, some of the mathematical notation got lost (at least with my PDF viewer), e.g. p. 10

Cheers,

Ingo

PS: When @MSchnei and I wrote [a python package for pRF mapping](https://github.com/ingo-m/pyprf) two years ago we totally didn't know about `popeye` :) Funny how some of the solutions are a bit similar (e.g. use of cython and multiprocessing module, although `popeye` is definitely more elaborate and more object oriented ;) )

**Comment by kdesimone** [comment]
Hi,

Thanks for writing! You're right on the MPRAGE and TR, for sure. I'd spotted the TR typo but no one has pointed out the MPRAGE typo—thanks for that!  As for the formulations, yes those seem to be a function of things out of our control, at least for the preprint ...

As for your question—remember that the temporal pRF component is distinct from the double-gamma HRF. We pass the stimulus through the sustained and transient filters, take the weighted sum of those according to a mixture parameter, and then convolve this with the HRF to estimate the BOLD response.

But yes, your question is a good one—is our temporal pRF model biologically plausible? This is the figure that motivated much of our work and model (Maunsell et al., 1999):
<img width="833" alt="screen shot 2018-09-05 at 2 55 00 pm" src="https://user-images.githubusercontent.com/1775079/45115351-9c584a80-b11d-11e8-9454-7d6a8c8cf0d1.png">

It seems clear to me that there's a sustained component in the P response that is not in the M response. We modeled this sustained component as a Gaussian that slowly turns on and then off with the pulse of light. From there, it seemed natural (simple?) to express the transient component as its first derivative that rapidly turns on and off during the pulse. We then extended this sort of stimulus regime to make it more amenable to the timescale of BOLD measurments. That is, we turned the single pulse of light into a series of pulses over time—aka, flicker.

It's also clear from that figure that both M and P responses contain some transient component. Our model doesn't address this, but hopefully extensions of the model can.

Another way of thinking about the model is in terms of temporal frequency sensitivity. The frequencies a Gaussian passes will depend on its location and dispersion, but certainly the first derivate of an arbitrarily configured Gaussian will be sensitive to frequencies twice that of the Gaussian from which derives. After all, the Gaussian has one lobe, its first derivative has two. You need at least two frequencies to differentiate those responses, but the exact frequencies probably don't matter all that much.
