### ISSUE TITLE
Error when running the demo

### ISSUE THREAD

**Issue by mdunne34** [kdesimone/popeye#60]
Hi,

I tried running the demo in both python 2.7.13 and 3.6 and popeye '0.5.2' and got the following error after starting gradient descent:

`
The gridfit solution was [-10.           0.           5.25         0.           0.70969052
  -0.47236134], starting gradient descent ...
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/share/pkg/python/2.7.13/install/lib/python2.7/site-packages/popeye/og_hrf.py", line 259, in __init__
    voxel_index, Ns, auto_fit, verbose)
  File "/share/pkg/python/2.7.13/install/lib/python2.7/site-packages/popeye/base.py", line 272, in __init__
    self.estimate
  File "/share/pkg/python/2.7.13/install/lib/python2.7/site-packages/popeye/onetime.py", line 174, in __get__
    val = self.getter(obj)
  File "/share/pkg/python/2.7.13/install/lib/python2.7/site-packages/popeye/base.py", line 355, in estimate
    return self.gradient_descent[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
`
Do you know why I might be getting this error? I ran the demo exactly as it was written. Let me know if you need more information.

Thanks,
Matt

**Comment by kdesimone** [comment]
Hi Matt,

I just installed popeye via pip on a fresh conda env and got the right
result. How did you try to install it?

[image: Screen Shot 2019-03-11 at 7.36.49 PM.png]

**Comment by mdunne34** [comment]
I got it to run correctly by changing verbose to 0 or 1, it seems to only crash for me when verbose is set to 2. I installed it via pip on my PC through anaconda prompt and it was also installed on an HPC cluster. Changing verbose fixed it for both though. Does it run correctly for you with verbose=2?

**Comment by psychonomic** [comment]
Yes I got it to print with verbose=2. 

It's hard to say why you'd get that error with the print.

**Comment by kdesimone** [comment]
Yes I got it to run fine with verbose=2.

It's hard to say why you'd get that error with the print.
