### ISSUE TITLE
`double_gamma_hrf` parameter `tr` changes the delay of the HRF peak

### ISSUE THREAD

**Issue by noahbenson** [kdesimone/popeye#63]
So we noticed recently that if we adjust the TR of the `double_gamma_hrf`, the peaks appear to be scaled in time; e.g.:

```python
import matplotlib.pyplot as plt
from popeye.utilities import double_gamma_hrf

def hrf_xy(tr):
    x = np.arange(0, 32, tr)
    y = double_gamma_hrf(0, tr)
    return (x, y / np.max(y))

for (tr, color) in zip([1, 2, 4], ['r', 'g', 'b']):
    (x, y) = hrf_xy(tr)
    plt.plot(x, y, color + '.-')
```
Yields the following plot:
![image](https://user-images.githubusercontent.com/2005723/64433364-51547880-d08c-11e9-8fe4-4235426c1a03.png)

It looks to me like this is due to the `alpha_1` and `alpha_2` parameters getting scaled by the `tr` parameter in the `double_gamma_hrf` function. Removing these scale factors, we get this plot:
![image](https://user-images.githubusercontent.com/2005723/64434594-e5274400-d08e-11e9-9369-f1488821b68d.png)

This is more what I would expect. My intuition is that the scaling by the `tr` parameter might be a leftover bit from a previous iteration of the function that sampled time differently (or something like that). Regardless, before I submit a pull request, I wanted to check that I haven't missed a reason for the scaling.

Also worth noting that, assuming my interpretation is right, this likely has not affected anyone's fitting results very much because the delay parameter still seems to work to fit the time-delay of the HRF.

**Comment by kdesimone** [comment]
OK thanks for spotting this. Can you PR?

**Comment by noahbenson** [comment]
Great, thanks!
